### ISSUE TITLE
Question about preprocessing for proximity encodings

### ISSUE THREAD

**Issue by THINK2TRY** [zaixizhang/ANS-GT#2]
Hi, thanks for the excellent work. I am curious about the cost of preprocessing step. It seems that both time and space complexity to obtain the proximity encodings are O(n^2). How do you scale this step to large-scale graphs, like Ogbn-products, as reported in the paper?

**Comment by zaixizhang** [comment]
Hi, thanks for your question! Since the preprocessing steps only need to be calculated once before training. The time and space complexity is still affordable.

**Comment by timkaler** [comment]
Could you please explain how you produced the results for ogbn-products that are reported in your paper. I do not think it is reasonable for you to have used the present code (that has, as I understand it, a preprocessing overhead of N^2 ) on a dataset with 2.5 million vertices. I would prefer to know precisely what you did, as opposed to guessing, so that it is possible to make fair comparisons with your work.
